### PR TITLE
On Windows set realpath as _fullpath alias

### PR DESCRIPTION
**Pull request by mrv96**
This PR aims to fix https://github.com/msteveb/jimtcl/issues/91 (at least partially) using workaround described here: https://sourceforge.net/p/mingw/patches/256/#ef43

I don't know jimtcl architecture, probably these changes have to be included in the project in a better way. Maintainers are welcome to edit my branch introducing all necessary adjustments.

### CODE REVIEW

**Comment by mrv96** [comment]
I don't know why some normalize tests fail, but the out values are not abnormal. I ask to people more expert than me to contribute please.

**Comment by msteveb** [comment]
I suspect the problem is that it returns backslashes but file tail and file dirname want to see forward slashes

**Comment by mrv96** [comment]
Should this handled by this PR? I mean, I know that other TCL procedures needs forward slashes, but windows path uses backslash, this is a Windows characteristic, not an issue.

To solve this issue I use in my scripts: `set path [string map {\\ /} $WindowsPath]`

Maybe we should modify unit tests adding the above string map procedure call?

**Comment by msteveb** [comment]
For simplicity jimtcl expects forward slashes everywhere. See pwd in jim-file.c. You should do the same

**Comment by mrv96** [comment]
@msteveb Is it ok now? Do you prefer that i fixup the last commit into the first one?

**Comment by msteveb** [comment]
It's fine as-is since I will do some consolidation before merging

**Comment by msteveb** [comment]
I created https://github.com/msteveb/jimtcl/tree/win-realpath Let me know if that works for you

**Comment by mrv96** [comment]
It looks good for me. I'm a little bit concerned about MAXPATHLEN value. Shouldn't JIM_PATH_LEN value forced to 260 in Windows?

Moreover, according to the realpath define here https://sourceforge.net/p/mingw/patches/256/#ef43, IMO JimRealPath len argument doesn't need the +1 here: https://github.com/msteveb/jimtcl/blob/a6186ab240d4ff59ab1f32e1a4f92377e842696e/jim-file.c#L389

**Comment by msteveb** [comment]
Yes, I think agree that + 1 is not needed there. Regarding 260, I'm not sure. Not really too familiar with Windows. How does it work with new filesystems and longer paths? Is that not possible or not via these APIs? In any case it should be consistent everywhere, so if we change it it should be in jim.h

**Comment by mrv96** [comment]
I'm not expert too in Windows. From https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry I understand that windows.h defines MAX_PATH with a value of 260, and loger paths must be enabled manually on the OS.

Since JIM_PATH_LEN is used only if PATH_MAX is not defined, on Windows i suppose that should be set to 260 to be safe.

P.S. I use MinGw for Windows which defines both MAX_PATH and PATH_MAX with the same value, hence PATH_MAX should be fine for Windows too, without the necessity to use MAX_PATH explicitly.

________________________________

**Comment by msteveb** [comment]
Thanks, so I think that will be ok for now unless someone more knowledgeable comes along. I will merge the changes

**Pull request closed without merging**
