### PR TITLE
SSL/TLS stream support via LibreSSL

### PR DESCRIPTION
**Pull request by dimkr**
```tcl
set s [socket stream.server 127.0.0.1:8443]
set c [[$s accept] ssl -server certificate.pem key.pem]
puts [$c gets]
```

### CODE REVIEW

**Comment by msteveb** [comment]
Very interesting. I'd like to see at least one example, perhaps in examples/
Can we send an https request and get the response?
Also, --full should probably silently ignore ssl not being available.
And there seems to be a bug around line 1052 of jim-aio.c 
Should check for argc != 2, not argc != 1
That's all from a very quick review for now

**Comment by dimkr** [comment]
> Can we send an https request and get the response?

Yes; I even ran a HTTPS server using [jimhttp[(https://github.com/dbohdan/jimhttp), wth a [new connection lambda](https://github.com/dbohdan/jimhttp/commit/1417f8283c1916e4bc1b765458c9894df140941e#diff-855ef05c4f01b4e9be284e6d4e781deeR284) that wraps the socket with a TLS stream: both client and server work.

I'll do my best to address the points you raised later today or tomorrow.

**Comment by msteveb** [comment]
Sorry it's taken so long. Another few comments:
- I'd prefer to "cc-check-function-in-lib TLSv1_2_method ssl" since Apple has deprecated openssl since 10.7 and doesn't have support for this.
- In JimAioSetError(), shouldn't we check af->ssl before using ERR_get_error()? And I'm worried about a left-over ssl error, or an error for another file descriptor confusing things.
- It's a shame that the ssl context needs to be created during Jim_aioInit() even if ssl is never used. Maybe better to defer to an explicit init, or the first time ssl is used.
- The two paths for ssl vs non-ssl reading/writing is messy. I would like to see use of a thin layer that either uses fread/fgetc/fwrite/fputc or SSL_read/SSL_write as appropriate.
- The documentation needs updating.
Everything else looks reasonable.

Thanks, Steve.

**Comment by msteveb** [comment]
Something like this: https://github.com/msteveb/jimtcl/commits/dimkr-libressl

**Comment by dimkr** [comment]
I'll pull your changes first - there's quite a bit of refactoring and testing to do :)

**Comment by dimkr** [comment]
Done :+1:

**Comment by msteveb** [comment]
Great. Can you explain why you want to fall through to strerror() if there is no ssl errror in 849e975b?
For an ssl socket, the only operations are ssl operations, so why would strerror() return anything useful?

**Comment by dimkr** [comment]
Yes, I want it to fall through.As far as I understand, according to the OpenSSL documentation, it is not guaranteed that the error code isn't 0 (unlike errno, which is reliable), because some errors don't have a matching enum value.

**Comment by msteveb** [comment]
So you are saying that you could get an error, but ERR_get_error() returns 0? If this is so, surely strerror() isn't going to give something meaningful. Can we just return "unknown SSL error" instead?
It would be nice to have some test cases for these conditions, but I know it can be hard to construct them.

**Comment by dimkr** [comment]
I spent more time thinking about this and I guess you're right. Now, there's a fallback "unknown error" thingy and I expanded the fops structure to make things more elegant.

**Comment by msteveb** [comment]
I think we are almost there. I've pushed a rolled-up patch to https://github.com/msteveb/jimtcl/commits/dimkr-libressl

**Comment by dimkr** [comment]
```
I think we are almost there
```

Any remaining tasks?

**Comment by msteveb** [comment]
I just have the one comment about HAVE_SOCKETPAIR in aio_cmd_ssl

(Note, I made a typo when pushing the new branch, so check the branch here: https://github.com/msteveb/jimtcl/commits/dimkr-librssl)

**Comment by dimkr** [comment]
Merged your changes and took care of kicking that HAVE_SOCKETPAIR.

**Comment by msteveb** [comment]
Merged. Thanks!

**Pull request closed without merging**
