### PR TITLE
 Make 'quit' a synonym of 'exit'

### PR DESCRIPTION
**Pull request by prpr19xx**
It's easier to type q, tab as well as not having to remember whether it's exit or quit.

### CODE REVIEW

**Comment by dbohdan** [comment]
This feature seems unnecessary.  There is already a quick way to exit Jim Tcl on \*nix: with Ctrl + D.

**Comment by dbohdan** [comment]
If you specifically want a short command, you can put `alias q exit` in `~/.jimrc` and avoid the need to press Tab.

**Comment by prpr19xx** [comment]
Jim is multi-platform. Ctrl-D isn't. So that's a non-starter. Also, I view that as a more 'dirty' termination than 'exit', rightly or wrongly.
Putting aliases in on every machine you run this thing on is a whole lot more work than just adding it to the code.
I can't really believe that adding two pointers to a pre-existing table, and a 5 byte string is that contentious. It has about the most miniscule cost you could imagine. It doesn't affect any previous behaviour and no-one is forcing YOU to use it - it has zero effect on anyone who doesn't want or need it.
Writing this has cost far more than adding this tiny little enhancement ever will.
If the benefit (to somebody) outweighs the cost (to anybody) then it should be done. Clearly this statement is true.

**Comment by dbohdan** [comment]
The cost I would consider is not the five bytes but the precedent of adding a completely identical but differently named command to the core because a user finds it ergonomic.  (I want to emphasize that this is not personally against you.  I am suggesting a general principle.)  Many useful REPL shorthands for common commands are possible, and everyone has their own, which may conflict with each other.  For this reason I think the proper place for them is in a library one sources from `~/.jimrc` or perhaps an extension if it's an embedded system.

> Also, I view that as a more 'dirty' termination than 'exit', rightly or wrongly.

Specifically in Jim's case, `Jim_InteractivePrompt` treats `exit` and EOF very similarly.  You don't lose your history or anything like that.

**Comment by msteveb** [comment]
I'm with @dbohdan on this one. There is a reason that many applications have user configuration (jim has .jimrc, vim has .vimrc, etc.) - to support different user preferences. I regularly pick up my "dot files" and copy them from one system to the other to keep my preferences. This is normal.

**Pull request closed without merging**
