### PR TITLE
Fix environment argument for Windows CreateProcess

### PR DESCRIPTION
**Pull request by evanhunter**
Required a different environment format - was previously causing errors and failing to execute some commands

This is what has been causing the failures on appveyor build tests

### CODE REVIEW

**Comment by msteveb** [comment]
Take a look at JimBuildEnv(). You will see that this already builds the environment in the correct form (which is why we pass save_environ[0]).
But, I think you're on to something here. If $::env is unset we don't build the environment and just return Jim_GetEnviron(). Could this not be in the correct form?
And also, if $::env is empty, this definitely won't be correct since save_environ[0] will be NULL.

**Comment by msteveb** [comment]
Actually, in the latter case NULL will be passed to CreateProcess() so it will use the caller's environment. This is not correct, but shouldn't cause the behaviour we are seeing.

**Comment by evanhunter** [comment]
No - Jim_GetEnviron returns the variable "environ" which is in the wrong format. Hence the problem.

**Comment by evanhunter** [comment]
My code works correctly because when  $::env is:

* set :  JimBuildEnv() creates a array of pointers similar to "environ" variable but it happens that all the strings are in one block as needed by CreateProcess. My code parses the array and re-creates it's own version of the single block

* unset: Jim_GetEnviron() just returns the "environ" variable and this is not in one single block, so passing it to the CreateProcess function causes it to fail, as it is looking for the double null. In this case my code parses the variables and puts them into one block as needed.

**Comment by msteveb** [comment]
Can you clarify:

> set : JimBuildEnv() creates a array of pointers similar to "environ" variable but it happens that all the strings are in one block as needed by CreateProcess. My code parses the array and re-creates it's own version of the single block

JimBuildEnv() creates the variables in a single block with a double null terminator by design. This should be in the format that CreateProcess() wants. Why do you think it isn't?

**Comment by evanhunter** [comment]
Sure:  
JimBuildEnv() output for 3 variables : one block of memory
[ var1ptr, var2ptr, var3ptr, var1data, null, var2data, null, var3data, null, null ]

Hence giving CreateProcess a pointer to var1data (aka save_environ[0]) is giving the single block of null terminated strings with an extra over-all null terminator - as required.

"environ" variable for 3 variables : 4 blocks of memory
[ var1ptr, var2ptr, var3ptr]
other data
[var1data, null] 
other data
[var2data, null]
other data
[var3data, null]

Hence this case is not providing what Create process needs.

**Comment by evanhunter** [comment]
In both cases my code starts at var1ptr and parses in the same way, creating a single memory block containing all values

**Comment by msteveb** [comment]
I'm not questioning whether your code works, but its a lot of extra code when what is there is almost correct already. Anyway, I've pushed a more minimal fix. Please try it out.

**Comment by evanhunter** [comment]
Ok - will check

**Pull request closed without merging**
