### PR TITLE
Array fixes and tests

### PR DESCRIPTION
**Pull request by evanhunter**
Changed 'array exists' to actually check if the variable is an array
Add more instructive error messages for two error cases
Added some more tests for array command

### CODE REVIEW

**Comment by msteveb** [comment]
I'm not really convinced of the usefulness of some of these errors. But I guess Tcl compatibility doesn't hurt. But did you compare against Tcl? At least on Tcl 8.6 1.18 and 1.19 fail. We should be compatible there.
Also, perhaps Jim_DictInfo() should be modified to set the tcl result rather than sending to stdout.

**Comment by evanhunter** [comment]
will do

**Comment by evanhunter** [comment]
See new commit 
- Makes the system match tclsh and tests pass on both jimsh and tclsh
- Removes the new error messages since they don't match tclsh
- Removes a couple of other error returns which don't match tclsh
- Fixes Jim_DictInfo() to match tclsh

**Comment by msteveb** [comment]
I adjusted the output to be more Tcl compatible. Included the average search distance and removed the trailing newline.
Applied. Thanks!

**Pull request closed without merging**
