### PR TITLE
Improve the 'clock format' command so it is closer to official API spec.

### PR DESCRIPTION
**Pull request by evanhunter**
Add tests for clock commands to cover all current code paths

### CODE REVIEW

**Comment by msteveb** [comment]
How much of this is really necessary? I think the clock implementation in Tcl 8.6 has become a mess.

- As far as I can tell, the locale and timezone options are being ignored.
- There is no need for Jim_SetResultWide(). The object created by Jim_NewIntObj() is already a jim_wide.

**Comment by evanhunter** [comment]
The point of the locale/timezone options was to allow compatibility with official TCL code - even if the arguments are not used internally, at least the code would run.

Currently, unless any other options in any position will cause the code to fail, even if the -format option is supplied.

It should not be too expensive to at least minimally hook the timezone/locale up to the underlying OS.  
However the way that the official TCL allows full ability to define custom locales would be pretty heavyweight.

I'll remove the Jim_SetResultWide change.
I'll also check out the windows failure - I think I forgot a file in the commit

**Comment by msteveb** [comment]
The -gmt option is probably useful. Can we just put everything else in a Tcl wrapper in tclcompat.tcl?

**Comment by msteveb** [comment]
Thanks. I finally integrated support for -gmt into both clock format and clock scan.

**Pull request closed without merging**
