### PR TITLE
Memory & Resource fixes

### PR DESCRIPTION
**Pull request by evanhunter**
Hi Steve,

Here's some changes to fix:
- a memory leak
- possible null non-termination problems with snprintf
- Usage of malloc/realloc/free rather than Jim_ variants
- Prevention of double-closing file descriptors

Regards,

Evan

### CODE REVIEW

**Comment by msteveb** [comment]
Thanks for the commits. A few comments.

- Why do you think buffers need terminating after snprintf()? snprintf() does this already
- We have to use malloc/free in jim-interactive since if we use linenoise, it uses malloc/free
- The changes to realloc in jim-sqlite.c look fine
- Regarding the changes in jim-exec.c, do you have any test cases that show the problem? The assignments around line 1072 will do nothing since we return just afterwards

**Comment by evanhunter** [comment]
>> Why do you think buffers need terminating after snprintf()? snprintf() does this already

I think this was a combination of my assuming snprintf is broken like strncpy and remembering 
that on some platforms (MSVC++) the termination is not guaranteed.
After re-reading documentation, I've found that starting with MSVC 2015, snprintf is finally properly C99
compliant, but that the _snprintf variant is not.
Hence, the proper change is in jim-win-32-compat.h/jimsh0.c to remove:
#define snprintf _snprintf

>> We have to use malloc/free in jim-interactive since if we use linenoise, it uses malloc/free
Sure.

>> Regarding the changes in jim-exec.c, do you have any test cases that show the problem? The assignments around line 1072 will do nothing since we return just afterwards

I am looking into this - I think it was found with either the MSVC or Clang static analyzer - I don't remember.  The extra assignments around 1072 were just paranoia - I agree they are not needed

**Comment by msteveb** [comment]
OK. I'll take the change to remove _snprintf and the one place in jim-exec.c that a file descriptor is closed and may need to be set to -1.

**Comment by msteveb** [comment]
I've pushed a different fix for the signal handler memory allocation. Now all of these are addressed. Closing.

**Pull request closed without merging**
