### PR TITLE
Improve Object-Oriented inheritance capabilities and add tests for ob…

### PR DESCRIPTION
**Pull request by evanhunter**
…ject orientation

Allows:
- Multi-level inheritance
- Multiple inheritance

### CODE REVIEW

**Comment by msteveb** [comment]
Interesting. Could be confusion between baseclass, baseclasses and allbaseclasses. Should it be baseclass ?-all? ?-below? or something similar?

**Comment by msteveb** [comment]
Also, the comments/licence at the top of tests/jimoo.test seem wrong

**Comment by dbohdan** [comment]
TclOO uses the term "superclass".

--
Sent from my mobile device.

**Comment by evanhunter** [comment]
Please feel free to suggest better names for the variables/procs I'll change the comment/license - I accidentally copied that from another tcl test case.

**Pull request closed without merging**
