### PR TITLE
jim-win32.c: Add command win32.MessageBox

### PR DESCRIPTION
**Pull request by dbohdan**
This adds a command for displaying a graphical message box via `MessageBoxA`, which I found useful.

### CODE REVIEW

**Comment by msteveb** [comment]
Seems fine to me. I never use the Windows support, so I don't have much of an opinion. I guess it would be nice to use an enum for the type rather than an integer.

To get the win32 module to build on mingw32, I needed to make the following changes:

```
diff --git a/jim-win32.c b/jim-win32.c`
index 1a6a3b6..3218edc 100644
--- a/jim-win32.c
+++ b/jim-win32.c
@@ -37,7 +37,7 @@
 /* Apparently windows.h and cygwin don't mix, but we seem to get
  * away with it here. Use at your own risk under cygwin
  */
-#if defined(__CYGWIN__)
+#if defined(__CYGWIN__) || defined(__MINGW32__)
 #define WIN32_LEAN_AND_MEAN
 #include <windows.h>
 #endif
@@ -54,6 +54,10 @@
 #pragma comment(lib, "psapi")
 #endif /* _MSC_VER >= 1000 */

+#if _WIN32_WINNT < 0x600
+    #define GetTickCount64 GetTickCount
+#endif
+
 static Jim_Obj *
 Win32ErrorObj(Jim_Interp *interp, const char * szPrefix, DWORD dwError)
 {
```

**Comment by dbohdan** [comment]
>I guess it would be nice to use an enum for the type rather than an integer.

I thought about that but decided it is better to define and add the `MB_*` constants on the Tcl side. It will be forward-compatible if new flags are added.

>To get the win32 module to build on mingw32, I needed to make the following changes:

Same here with MSYS2/MinGW-w64 on Windows XP and 10. Do you want me to commit these changes and include them in the PR or will you commit them?

On a related note, [AppVeyor](https://www.appveyor.com/) has classic MinGW and MSYS2 support. Would you be interested in an AppVeyor config for Windows CI? Other than the host OS, it is very similar to Travis CI in how it works.

**Comment by msteveb** [comment]
I'll do it. Sure, re AppVeyor

**Comment by msteveb** [comment]
Applied. Thanks!

**Pull request closed without merging**
