### PR TITLE
Add AppVeyor CI

### PR DESCRIPTION
**Pull request by dbohdan**
This runs AppVeyor CI to build Jim (with the additional extensions oo, tree, binary, tclprefix, zlib <s>and win32</s>), run the tests and package the Windows binary for every commit. However, the tests currently fail:

```
exec-3.5 ERR redirecting output to file
At      : exec.test:107
Expected: 'rc=ok return result=First line
Second line'
Got     : 'rc=error result=/usr/bin/echo: write error: Bad file descriptor'
exec-3.6 ERR redirecting output to file
At      : exec.test:112
Expected: 'rc=ok return result=First line
Second line'
Got     : 'rc=error result=/usr/bin/echo: write error: Bad file descriptor'
exec-4.3 ERR redirecting output and stderr to file
At      : exec.test:139
Expected: 'rc=ok return result={} {first line
foo bar}'
Got     : 'rc=error result='
exec-12.1 ERR reaping background processes
At      : exec.test:345
Expected: '0'
Got     : 'couldn't'
exec-15.5 ERR standard error redirection
At      : exec.test:388
Expected: 'rc=ok return result=First line
foo bar'
Got     : 'rc=error result='
       exec.test: Total    76   Passed    71  Skipped     0  Failed     5
------------------------------------------------------------
FAILED: 5
	exec.test:107	exec-3.5
	exec.test:112	exec-3.6
	exec.test:139	exec-4.3
	exec.test:345	exec-12.1
	exec.test:388	exec-15.5
------------------------------------------------------------
```

Each of the failed tests involves [exec] appending the output of a command to a file. E.g. (this is the MSYS2 shell),

```
$ ./jimsh.exe -e 'exec echo "First line" >> new.file' && cat new.file
/usr/bin/echo: write error: Bad file descriptor
```

However, the `>` redirect works:

```
$ ./jimsh.exe -e 'exec echo "First line" > new.file' && cat new.file

First line

```

At a glance, I can't find the precise reason why this happens but it looks like a bug. I'll investigate later.

### CODE REVIEW

**Comment by dbohdan** [comment]
Log: https://ci.appveyor.com/project/dbohdan/jimtcl.

**Comment by dbohdan** [comment]
Okay, now that I've properly activated the extensions (there was a quoting error previously), I see zlib errors as well:

```
zlib-1.7 ERR zlib inflate usage 4
At      : zlib.test:43
Expected: 'buffer size must be 0 to 2147483647'
Got     : 'buffer size must be 0 to 0x7fffffff'
zlib-2.3 ERR zlib deflate/inflate bad size
At      : zlib.test:55
Expected: 'buffer size must be 0 to 2147483647'
Got     : 'buffer size must be 0 to 0x7fffffff'
zlib-3.7 ERR zlib gunzip usage 6
At      : zlib.test:87
Expected: 'buffer size must be 0 to 2147483647'
Got     : 'buffer size must be 0 to 0x7fffffff'
       zlib.test: Total    26   Passed    23  Skipped     0  Failed     3
------------------------------------------------------------
FAILED: 3
	zlib.test:43	zlib-1.7
	zlib.test:55	zlib-2.3
	zlib.test:87	zlib-3.7
------------------------------------------------------------
```

**Comment by dbohdan** [comment]
Fixed the zlib error message tests, which failed when `MAX_INT` was in hex. Whether it is in hex or in decimal appears to depend on the GCC version, not the platform; it's in hexadecimal on my desktop Linux (openSUSE Tumbleweed) and Windows (MSYS2) but in decimal on Travis CI, which runs Ubuntu 12.04.

**Comment by msteveb** [comment]
Thanks. I've taken these changes with some small tweaks. If you can work out why the exec tests are failing on AppVeyor, that would be great.

**Comment by msteveb** [comment]
I imagine the problem is CreateFile() in JimOpenForWrite() when append == 1.
I wonder if we should be setting FILE_ATTRIBUTE_NORMAL rather than 0.

**Pull request closed without merging**
