### PR TITLE
Fix warnings when building win32 module and add module to appveyor build

### PR DESCRIPTION
**Pull request by evanhunter**

### CODE REVIEW

**Comment by msteveb** [comment]
This is fine, but I still see some warnings:
```
gcc -Wall  -I. -g -O2 -fno-unwind-tables -fno-asynchronous-unwind-tables -DUSE_UTF8    -c -o jim-win
32.o jim-win32.c
jim-win32.c: In function 'Win32_ShellExecute':
jim-win32.c:109:9: warning: cast from pointer to integer of different size
jim-win32.c:112:13: warning: cast from pointer to integer of different size
jim-win32.c: In function 'Win32_GetActiveWindow':
jim-win32.c:166:5: warning: cast from pointer to integer of different size
```

**Comment by evanhunter** [comment]
Hmm - yeah - they are on appveyor too - but not on my machine - I'll fix them

**Comment by evanhunter** [comment]
Fixed now

**Comment by msteveb** [comment]
ptrdiff_t is quite dubious, but it will do for now. Applied.

**Pull request closed without merging**
