### PR TITLE
add new option "timezone" to "clock format"

### PR DESCRIPTION
**Pull request by frgm**

### CODE REVIEW

**Comment by msteveb** [comment]
Thanks. The doc changes are fine. Please don't include functionality changes in the same pull request. I'm very wary about using setenv(). Please move that commit to a separate issue and it can be discussed there.

**Comment by frgm** [comment]
ok, now it's only one commit;
doc changes - https://github.com/msteveb/jimtcl/pull/29

**Comment by frgm** [comment]
How about to use simply UTC time via gmtime() ?
(and via opt -utc or -u)

**Comment by frgm** [comment]
... or like [lua](http://www.lua.org/manual/5.3/manual.html#pdf-os.date) ("If format starts with '!'"):
```diff
--- a/jim-clock.c
+++ b/jim-clock.c
@@ -25,8 +25,10 @@ static int clock_cmd_format(Jim_Interp *interp, int argc, Jim_Obj *const *argv)
 {
     /* How big is big enough? */
     char buf[100];
+    const struct tm *tm;
     time_t t;
     long seconds;
+    int len;
 
     const char *format = "%a %b %d %H:%M:%S %Z %Y";
 
@@ -35,7 +37,7 @@ static int clock_cmd_format(Jim_Interp *interp, int argc, Jim_Obj *const *argv)
     }
 
     if (argc == 3) {
-        format = Jim_String(argv[2]);
+        format = Jim_GetString(argv[2], &len);
     }
 
     if (Jim_GetLong(interp, argv[0], &seconds) != JIM_OK) {
@@ -43,7 +45,20 @@ static int clock_cmd_format(Jim_Interp *interp, int argc, Jim_Obj *const *argv)
     }
     t = seconds;
 
-    if (strftime(buf, sizeof(buf), format, localtime(&t)) == 0) {
+    if (*format == '!') {
+        tm = gmtime(&t);
+        format++;
+        len--;
+    } else {
+        tm = localtime(&t);
+    }
+
+    if (argc == 3 && !len) {
+        Jim_SetResultString(interp, "empty string", 12);
+        return JIM_ERR;
+    }
+
+    if (strftime(buf, sizeof(buf), format, tm) == 0) {
         Jim_SetResultString(interp, "format string too long", -1);
         return JIM_ERR;
     }
@@ -59,15 +74,29 @@ static int clock_cmd_scan(Jim_Interp *interp, int argc, Jim_Obj *const *argv)
     char *pt;
     struct tm tm;
     time_t now = time(0);
+    int len;
+    const char *format;
 
     if (!Jim_CompareStringImmediate(interp, argv[1], "-format")) {
         return -1;
     }
 
-    /* Initialise with the current date/time */
-    localtime_r(&now, &tm);
+    format = Jim_GetString(argv[2], &len);
+    if (*format == '!') {
+        gmtime_r(&now, &tm);
+        format++;
+        len--;
+    } else {
+        /* Initialise with the current date/time */
+        localtime_r(&now, &tm);
+    }
+
+    if (!len) {
+        Jim_SetResultString(interp, "empty string", 12);
+        return JIM_ERR;
+    }
 
-    pt = strptime(Jim_String(argv[0]), Jim_String(argv[2]), &tm);
+    pt = strptime(Jim_String(argv[0]), format, &tm);
     if (pt == 0 || *pt != 0) {
         Jim_SetResultString(interp, "Failed to parse time according to format", -1);
         return JIM_ERR;
```

**Pull request closed without merging**
